FROM eclipse-temurin:17

LABEL mentainer="shujaat.apple05@gmail.com"

WORKDIR /app

COPY target/blogs-rest-api-0.0.1-SNAPSHOT.jar /app/blogs-rest-api.jar

ENTRYPOINT ["java", "-jar", "blogs-rest-api.jar"]

