spring.application.name=blogs-rest-api
server.port=5000

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://rest-blogs.c9i48oo08iu0.ap-southeast-1.rds.amazonaws.com:1433;databaseName=blogs;encrypt=false
spring.datasource.username=SA
spring.datasource.password=MyStrongPass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings (optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.drop-impl=ignore

