spring.application.name=blogs-rest-api
server.port=8088

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=blogs;encrypt=false
spring.datasource.username=SA
spring.datasource.password=MyStrongPass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings (optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.drop-impl=ignore

spring.security.user.name=hussain
spring.security.user.password=Abc123
spring.security.user.roles=ADMIN
